### ISSUE TITLE
heap_3 v.s heap_2

### ISSUE THREAD

**Issue by jmfriedt** [feilipu/miniAVRfreeRTOS#7]
Thank you for your FreeRTOS example for AVR microcontrollers, I found it most useful to merge with the current (FreeRTOSv202212.01) version and get some basic examples running on an Atmega32U4 and simavr: most impressive what can be achieved on 2.5 KB RAM!

I was disappointed to see the vTaskList() application fail: tracing the issue, I found that the malloc() of heap_3.c is failing when vTaskList dynamically allocates memory in ``tasks.c``:
```
        pxTaskStatusArray = pvPortMalloc( uxCurrentNumberOfTasks * sizeof( TaskStatus_t ) ); 
        if( pxTaskStatusArray != NULL )
```
``pvPortMalloc`` returns NULL and the array is never filled, hence the lack of display of the task list. Using the more conservative (as I understand) heap_2.c, manually allocating memory on the heap instead of relying on avr-libc's malloc, allows for successfully executing the vTaskList call. I am using the heap_2.c from FreeRTOS with no modification.
Thank you.

**Comment by feilipu** [comment]
Adding [this line](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/src/variantHooks.cpp#L51) to your code, before initialising FreeRTOS, should help. The issue lies with the implementation of the AVR libc `malloc()`. It needs a little help to know what's what.

``` C
    // As the Task stacks are on heap before Task allocated heap variables,
    // the library default __malloc_heap_end = 0 doesn't work.
    __malloc_heap_end = (char *)(RAMEND - __malloc_margin);
```

**Comment by jmfriedt** [comment]
I can confirm this allows for heap_3.c to operate properly, after ``#include <stdlib.h>`` since this seems to be where the variable is defined. This does break somewhat the cross-platform portability of FreeRTOS software unless conditionally compiled e.g with ``#if defined (__AVR_ATmega32U4__)`` ... ``#endif``

Thanks
